import React, { Suspense } from "react";
import ReactDOM from "react-dom/client";
import "./index.css";
import ErrorBoundary from "./ErrorBoundary";
/* Explanation: This import block is the entry point for your entire frontend runtime and it also demonstrates multiple important JavaScript module concepts you will see everywhere in modern frontend development.

The syntax you are using is called ESM (ECMAScript Modules): `import ... from "..."` is how JavaScript loads code from other files in a standardized way (in the browser this is handled by the bundler/dev server like Vite, which rewrites and serves modules efficiently).There are three different “styles” of import shown here, and each has a specific meaning.
(1) Default + named import in one line: `import React, { Suspense } from "react";` means “take the module’s default export and call it React, and also take the named export called Suspense”. Default exports are written by the library author as `export default ...`; named exports are written as `export const Suspense = ...` (or `export { Suspense }`). Under the hood, this is not about performance, it is about what the module chooses to export. React is commonly imported as the default export, while `Suspense` is a specific feature exported by name.
(2) Default import only: `import ReactDOM from "react-dom/client";` means “take the default export from this module and call it ReactDOM”. This is how React exposes the browser renderer; in React 18+ you import from `react-dom/client` to access `createRoot`.
(3) Side-effect import: `import "./index.css";` looks strange because nothing is assigned to a variable. That is intentional: the purpose is the side effect of loading the CSS file. Vite processes this import, bundles the CSS, and ensures it is injected so styles apply globally; there is no JavaScript value you need from a CSS file, you just want it to be executed/loaded. Finally, `import ErrorBoundary from "./ErrorBoundary";` is another default import, but from your own file. Relative paths like `./ErrorBoundary` mean “a file next to this one”, while bare specifiers like `"react"` mean “a dependency from node_modules”.

This block also sets up key React concepts used later: React provides the component model (functions/classes that return UI), JSX support, and rendering semantics; `Suspense` is a React feature that lets you show fallback UI while some child is waiting (often because code is still downloading). `react-dom/client` connects your React component tree to a real DOM node using the modern root API. Importing CSS here ensures global styling is available from the first paint (important for UX and layout stability). Importing `ErrorBoundary` adds resilience: if a component throws during render, the app can show a controlled fallback instead of crashing to a blank page. */

// import AppRouter from "./AppRouter";
const AppRouter = React.lazy(() => import("./AppRouter"));
/* Explanation: This block introduces the second “kind” of import you will see in modern apps: dynamic imports via `import("...")`.The commented line (`import AppRouter from "./AppRouter";`) is a static import: it happens at module evaluation time, meaning as soon as this entry file loads, the bundler tries to load `AppRouter` too. Static imports are great for code that must be available immediately, but they can increase initial bundle size if the imported module pulls in many other modules (your router file imports or lazy-loads pages, providers, etc.).The active line uses `React.lazy(() => import("./AppRouter"))`. Here, `import("./AppRouter")` is a dynamic import expression: it returns a Promise that resolves to the module object when the chunk is downloaded. Bundlers treat this as a splitting point: they create a separate JS chunk for `./AppRouter` that can be fetched later. `React.lazy` wraps that Promise-based module loading into a component you can render like `<AppRouter />`. When React tries to render it for the first time, it triggers the download, and while that Promise is pending, React “suspends” rendering of that subtree. That is why `Suspense` is required above it: Suspense provides a fallback UI so the user sees something immediately rather than a blank screen.Think of this as a performance and scalability pattern: as the app grows, you keep the initial payload small and only pay the cost for features/routes when the user navigates to them. The trade-off is that you must handle loading states (fallback UI) and you should ensure critical routes/components are either preloaded or have a pleasant loading experience. */
const rootElement = document.getElementById("root");
const root = ReactDOM.createRoot(rootElement);
/* Explanation: This block connects React to the real HTML page.The browser initially loads `index.html`, which contains a single mount point like `<div id="root"></div>`. `document.getElementById("root")` returns that DOM node. `ReactDOM.createRoot(...)` creates a React “root” object that owns rendering into that node. Conceptually, the root is like a controller: once created, it manages reconciliation (React’s diffing algorithm) and updates the DOM efficiently whenever state/props change. In React 18, using `createRoot` (instead of the older `ReactDOM.render`) is the recommended API and enables improvements like concurrent rendering and better scheduling. Practical impact for development: you have a single place where the app is mounted, which makes the app architecture predictable; everything else in the project is “just components” rendered under this root. */
root.render(
  <React.StrictMode>
    <ErrorBoundary>
      <Suspense fallback={<div>Loading...</div>}>
        <AppRouter />
      </Suspense>
    </ErrorBoundary>
  </React.StrictMode>,
);
/* Explanation: This render block defines the top-level component tree and the runtime guarantees around it.`root.render(...)` is the moment your SPA becomes “alive”: React takes this tree, builds an internal representation, and paints it into the `#root` element. The wrappers each serve a different purpose. `React.StrictMode` is a development-only tool: it intentionally double-invokes certain behaviors (like running effects twice) to help you detect accidental side effects and unsafe patterns early; it does not affect production builds the same way. `ErrorBoundary` is your crash shield: if a descendant throws during rendering, it can stop the error from taking down the entire UI and instead show a controlled fallback (often with a “Try again” action). `Suspense` is the mechanism that makes lazy-loading usable: when `AppRouter` is still downloading, the fallback `<div>Loading...</div>` is rendered, so the user sees an immediate response rather than a blank page. Finally, `<AppRouter />` is the “composition root” of your actual application: it typically contains providers (Redux/Auth/Theme) and the route table, which enables the core SPA behavior: navigation changes what components render without doing a full page reload. This structure helps future development because it creates clear responsibilities: entry-point bootstrapping happens here; routing and app-wide context happens in `AppRouter`; page/layout components live elsewhere. */
// root.unmount();
/* Explanation: Unmounting is the opposite of mounting: it tells React to tear down the component tree, remove event listeners it added, and run cleanup functions from effects. Most SPAs never call `root.unmount()` because the app is expected to live for the whole lifetime of the browser tab. You would intentionally call it in special architectures such as micro-frontends (where an app is mounted/unmounted inside a host shell), integration tests (mount app, assert UI, unmount to isolate tests), or advanced tooling/hot-reload scenarios. Keeping this commented note here is fine as a learning aid, but it’s not required for normal operation. */
